<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use App\Models\User;

class RolePermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $permissions = [
            'view-admin',
            'accounts.view',
            'accounts.manage',
            'accounts.view_transactions',
            'journals.view',
            'journals.create',
            'journals.post',
            'journals.approve',
            'journals.reverse',
            // Periods
            'periods.view',
            'periods.close',
            'projects.view',
            'projects.manage',
            'funds.view',
            'funds.manage',
            'departments.view',
            'departments.manage',
            'customers.view',
            'customers.manage',
            'vendors.view',
            'vendors.manage',
            // Admin RBAC management
            'users.view',
            'users.create',
            'users.update',
            'users.delete',
            'users.assign',
            'roles.view',
            'roles.create',
            'roles.update',
            'roles.delete',
            'roles.assign',
            'permissions.view',
            'permissions.create',
            'permissions.update',
            'permissions.delete',
            'reports.view',
            // AR/AP
            'ar.invoices.view',
            'ar.invoices.create',
            'ar.invoices.post',
            'ar.receipts.view',
            'ar.receipts.create',
            'ar.receipts.post',
            'ap.invoices.view',
            'ap.invoices.create',
            'ap.invoices.post',
            'ap.payments.view',
            'ap.payments.create',
            'ap.payments.post',
            // Fixed Assets
            'assets.view',
            'assets.create',
            'assets.update',
            'assets.delete',
            'asset_categories.view',
            'asset_categories.manage',
            'assets.depreciation.run',
            'assets.depreciation.reverse',
            'assets.disposal.view',
            'assets.disposal.create',
            'assets.disposal.update',
            'assets.disposal.delete',
            'assets.disposal.post',
            'assets.disposal.reverse',
            'assets.movement.view',
            'assets.movement.create',
            'assets.movement.update',
            'assets.movement.delete',
            'assets.movement.approve',
            'assets.reports.view',
            // Cash Expenses
            'cash_expenses.view',
            'cash_expenses.create',
            'cash_expenses.post',
            // Banking
            'banking.view',
            'banking.cash_out',
            'banking.cash_in',
            // Inventory
            'inventory.categories.view',
            'inventory.categories.create',
            'inventory.categories.update',
            'inventory.categories.delete',
            'inventory.items.view',
            'inventory.items.create',
            'inventory.items.update',
            'inventory.items.delete',
            'inventory.stock_adjustments.view',
            'inventory.stock_adjustments.create',
            'inventory.stock_adjustments.update',
            'inventory.stock_adjustments.delete',
            'inventory.stock_adjustments.approve',
            'inventory.reports.view',
            'inventory.reports.export',
            // Control Accounts
            'control_accounts.view',
            'control_accounts.create',
            'control_accounts.edit',
            'control_accounts.delete',
            'control_accounts.reconcile',
            // Course Management
            'courses.view',
            'courses.create',
            'courses.update',
            'courses.delete',
            'course_categories.view',
            'course_categories.manage',
            'course_batches.view',
            'course_batches.create',
            'course_batches.update',
            'course_batches.delete',
            'enrollments.view',
            'enrollments.create',
            'enrollments.update',
            'enrollments.delete',
            // Course Financial Reports
            'course_financial_reports.view',
            'course_financial_reports.profitability',
            'course_financial_reports.receivables',
            'course_financial_reports.revenue_recognition',
            'course_financial_reports.payment_collection',
            'trainers.view',
            'trainers.create',
            'trainers.update',
            'trainers.delete',
            'payment_plans.view',
            'payment_plans.create',
            'payment_plans.update',
            'payment_plans.delete',
            'installment_payments.view',
            'installment_payments.create',
            'installment_payments.update',
            'installment_payments.delete',
            'revenue_recognition.view',
            'revenue_recognition.create',
            'revenue_recognition.update',
            'revenue_recognition.delete',
            // Reports
            'reports.payment.view',
            'reports.revenue.view',
            'reports.course.view',
            'reports.trainer.view',
            'reports.export',
            'reports.print',
            // Dashboards
            'dashboard.executive.view',
            'dashboard.financial.view',
            'dashboard.operational.view',
            'dashboard.performance.view',
        ];

        foreach ($permissions as $perm) {
            Permission::findOrCreate($perm);
        }

        $roles = [
            'superadmin' => $permissions,
            'accountant' => [
                'accounts.view',
                'accounts.view_transactions',
                'journals.view',
                'journals.create',
                'projects.view',
                'funds.view',
                'departments.view',
                'customers.view',
                'vendors.view',
                'reports.view',
                // AR/AP create/view
                'ar.invoices.view',
                'ar.invoices.create',
                'ap.invoices.view',
                'ap.invoices.create',
                'ar.receipts.view',
                'ar.receipts.create',
                'ap.payments.view',
                'ap.payments.create',
                // Cash Expenses
                'cash_expenses.view',
                'cash_expenses.create',
                // Banking
                'banking.view',
                'banking.cash_out',
                'banking.cash_in',
                // Control Accounts
                'control_accounts.view',
                'control_accounts.create',
                'control_accounts.edit',
                'control_accounts.reconcile',
                // Fixed Assets
                'assets.view',
                'asset_categories.view',
                'assets.reports.view',
                // Inventory
                'inventory.categories.view',
                'inventory.categories.create',
                'inventory.categories.update',
                'inventory.categories.delete',
                'inventory.items.view',
                'inventory.items.create',
                'inventory.items.update',
                'inventory.items.delete',
                'inventory.stock_adjustments.view',
                'inventory.stock_adjustments.create',
                'inventory.reports.view',
                'inventory.reports.export',
                // Course Management
                'courses.view',
                'courses.create',
                'course_categories.view',
                'course_batches.view',
                'course_batches.create',
                'course_batches.update',
                'course_batches.delete',
                'enrollments.view',
                'course_financial_reports.view',
                'course_financial_reports.profitability',
                'course_financial_reports.receivables',
                'enrollments.create',
                'trainers.view',
                'trainers.create',
                'payment_plans.view',
                'payment_plans.create',
                'installment_payments.view',
                'installment_payments.create',
                'installment_payments.update',
                'revenue_recognition.view',
                'revenue_recognition.create',
                'revenue_recognition.update',
                // Reports
                'reports.payment.view',
                'reports.revenue.view',
                'reports.course.view',
                'reports.trainer.view',
                'reports.export',
                // Dashboards
                'dashboard.financial.view',
                'dashboard.operational.view',
            ],
            'approver' => [
                'reports.view',
                // Posting permissions
                'journals.view',
                'journals.approve',
                'journals.post',
                'ar.invoices.post',
                'ap.invoices.post',
                'ar.receipts.post',
                'ap.payments.post',
                'cash_expenses.post',
                // Banking
                'banking.view',
                'banking.cash_out',
                'banking.cash_in',
                // Control Accounts
                'control_accounts.view',
                'control_accounts.reconcile',
                // Fixed Assets posting
                'assets.view',
                'assets.depreciation.run',
                'assets.depreciation.reverse',
                'assets.disposal.view',
                'assets.disposal.create',
                'assets.disposal.update',
                'assets.disposal.delete',
                'assets.disposal.post',
                'assets.disposal.reverse',
                'assets.movement.view',
                'assets.movement.create',
                'assets.movement.update',
                'assets.movement.delete',
                'assets.movement.approve',
                // Inventory (approval and management)
                'inventory.categories.view',
                'inventory.categories.create',
                'inventory.categories.update',
                'inventory.categories.delete',
                'inventory.items.view',
                'inventory.items.create',
                'inventory.items.update',
                'inventory.items.delete',
                'inventory.stock_adjustments.view',
                'inventory.stock_adjustments.create',
                'inventory.stock_adjustments.update',
                'inventory.stock_adjustments.delete',
                'inventory.stock_adjustments.approve',
                'inventory.reports.view',
                'inventory.reports.export',
                // Course Management (approval and management)
                'courses.view',
                'courses.create',
                'courses.update',
                'courses.delete',
                'course_categories.view',
                'course_categories.manage',
                'course_financial_reports.view',
                'course_financial_reports.profitability',
                'course_financial_reports.receivables',
                'course_financial_reports.revenue_recognition',
                'course_financial_reports.payment_collection',
                'course_batches.view',
                'course_batches.create',
                'course_batches.update',
                'course_batches.delete',
                'enrollments.view',
                'enrollments.create',
                'enrollments.update',
                'enrollments.delete',
                'trainers.view',
                'trainers.create',
                'trainers.update',
                'trainers.delete',
                'payment_plans.view',
                'payment_plans.create',
                'payment_plans.update',
                'payment_plans.delete',
                'installment_payments.view',
                'installment_payments.create',
                'installment_payments.update',
                'installment_payments.delete',
                'revenue_recognition.view',
                'revenue_recognition.create',
                'revenue_recognition.update',
                'revenue_recognition.delete',
                // Reports
                'reports.payment.view',
                'reports.revenue.view',
                'reports.course.view',
                'reports.trainer.view',
                'reports.export',
                'reports.print',
                // Dashboards
                'dashboard.executive.view',
                'dashboard.financial.view',
                'dashboard.operational.view',
                'dashboard.performance.view',
            ],
            'cashier' => [
                'reports.view',
                'journals.create',
                // Frontline cash operations
                'ar.receipts.view',
                'ar.receipts.create',
                'ap.payments.view',
                'ap.payments.create',
                // Banking
                'banking.view',
                'banking.cash_out',
                'banking.cash_in',
                // Customer management for cash operations
                'customers.view',
                // Inventory (limited access for stock adjustments)
                'inventory.items.view',
                'inventory.stock_adjustments.view',
                'inventory.stock_adjustments.create',
                'inventory.reports.view',
                // Course Management (limited access for enrollment)
                'courses.view',
                'course_categories.view',
                'course_batches.view',
                'enrollments.view',
                'enrollments.create',
                'course_financial_reports.view',
                'trainers.view',
                'payment_plans.view',
                'installment_payments.view',
                'installment_payments.update',
                'revenue_recognition.view',
                // Reports (limited access)
                'reports.payment.view',
                'reports.course.view',
                // Dashboards (limited access)
                'dashboard.operational.view',
            ],
            'auditor' => [
                'reports.view',
                // Read-only access to all modules for audit purposes
                'journals.view',
                'ar.invoices.view',
                'ar.receipts.view',
                'ap.invoices.view',
                'ap.payments.view',
                'cash_expenses.view',
                'banking.view',
                'control_accounts.view',
                'assets.view',
                'asset_categories.view',
                'assets.reports.view',
                // Inventory (read-only access)
                'inventory.categories.view',
                'inventory.items.view',
                'inventory.stock_adjustments.view',
                'inventory.reports.view',
                'inventory.reports.export',
                'customers.view',
                'vendors.view',
                'projects.view',
                'funds.view',
                'departments.view',
                'accounts.view',
                'accounts.view_transactions',
                'periods.view',
                // Course Management (read-only)
                'courses.view',
                'course_categories.view',
                'course_batches.view',
                'enrollments.view',
                'trainers.view',
                'course_financial_reports.view',
                'payment_plans.view',
                'installment_payments.view',
                'revenue_recognition.view',
                // Reports (read-only access)
                'reports.payment.view',
                'reports.revenue.view',
                'reports.course.view',
                'reports.trainer.view',
                'reports.export',
                // Dashboards (read-only access)
                'dashboard.executive.view',
                'dashboard.financial.view',
                'dashboard.operational.view',
                'dashboard.performance.view',
            ],
        ];

        foreach ($roles as $roleName => $perms) {
            $role = Role::findOrCreate($roleName);
            $role->syncPermissions($perms);
        }

        if ($admin = User::first()) {
            $admin->assignRole('superadmin');
        }
    }
}
